#!/usr/bin/with-contenv bash

# This is the init file used for adding os or pip packages to install lists.
# It takes advantage of the built-in init-mods-package-install init script that comes with the baseimages.
# If using this, we need to make sure we set this init as a dependency of init-mods-package-install so this one runs first

## Ubuntu
if [ -f /usr/bin/apt ]; then
    # apt dependencies packages from https://github.com/dotnet/dotnet-docker/blob/main/src/runtime-deps/8.0/noble/amd64/Dockerfile
    echo "icu-libs tzdata curl ca-certificates libatomic1 libc6 libgcc-s1 libicu74 libssl3t64 libstdc++6 tzdata-legacy zlib1g" >> /mod-repo-packages-to-install.list
fi
# Alpine
if [ -f /sbin/apk ]; then
    echo "Not supported for Alpine-based images yet."
    exit 1
fi

